# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.

require 'pry' # for debugging
require 'require_all' # for file loading

require 'cinch'
require 'cinch/extensions/authentication'
require 'sequel'
require 'factory_girl'

require_all 'lib/config'
require_all 'lib/helpers'
require_all 'lib/models'
require_all 'lib/plugins'
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  I18n.enforce_available_locales = false

  config.include FactoryGirl::Syntax::Methods

  config.before(:suite) do
    FactoryGirl.lint
  end

  config.before(:all) do
    FactoryGirl.reload
  end

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
